# Generated by Django 5.0.3 on 2024-04-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_budgetitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgettype',
            name='is_income',
        ),
        migrations.AddField(
            model_name='budgettype',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='INCOME', max_length=7),
        ),
    ]
